### ISSUE TITLE
Document generation to latex pdf misses some part of the documentation

### ISSUE THREAD

**Issue by MatthieuPERIN** [sbusard/pynusmv#1]
Hi, On linux ubuntu 15.04 64 bit, using python 2.7 & sphynx 1.3.4 the generation of documentation using 
 `make latexpdf` produces a valid pdf but the PYNUSMV REFERENCE (section 3) is almost empty (only the titles are present).

The PyNuSMV.tex latex is faulty here as the sections are empty there xhereas the html doc have these section filled !

**Comment by sbusard** [comment]
Hello,

First, PyNuSMV does not work with Python 2.x. You need Python 3.x to use it.
Second, I updated Sphinx conf.py file to use mock modules for NuSMV modules. This allows the documentation to be generated without compiling NuSMV. Your problem should be now solved assuming you use Python 3.3 or higher.
