### ISSUE TITLE
Associative arrays supported?

### ISSUE THREAD

**Issue by jaysnanavati** [sbusard/pynusmv#10]
Hi - I wanted to find out if associative arrays are supported by the input language.. as while not explicitly mentioned in : http://nusmv.fbk.eu/NuSMV/userman/v26/nusmv.pdf , I found pynusmv.collections.Assoc

**Comment by sbusard** [comment]
Hello,

Associative arrays are not supported by the input language. `pynusmv.collections.Assoc` is a Python wrapper around associative arrays used by NuSMV internally.

Note that the `pynusmv` project official repository moved to https://github.com/LouvainVerificationLab/pynusmv
