### ISSUE TITLE
Make the setup.py also install PyNuSMV objects

### ISSUE THREAD

**Issue by MatthieuPERIN** [sbusard/pynusmv#3]
Hi,

The present file src/setup.py is intend to install code as package.

But for now only the NuSMV interface is installed (pynusmv.nusmv.\* set) and not the pynusmv related objects (pynusmv.model._, pynusmv.init._, etc ).

It is confusing as the name of the module installed is "PyNuSMV".

Is it possible to add the PyNuSMV related objecte in this package setup in order to install all at once and use the build-in Python mechanism ?

**Comment by sbusard** [comment]
Hello,

I added all the pynusmv packages to the setup.py file such that all necessary python files are installed. The NuSMV shared library is also included, but the library is not usable without setting the correct value to (DY)LD_LIBRARY_PATH, pointing to the library. I found no way to export this path from the setup.py file.

**Comment by MatthieuPERIN** [comment]
Thanks a lot !

For the LD_LIBRARY_PATH it seems that all th e.so have to be linked together with complete path and yes, it seems difficult to achieve according to [this stackoverflow thread](http://stackoverflow.com/questions/856116/changing-ld-library-path-at-runtime-for-ctypes)

Maybe a solution is possible according to https://github.com/PyTables/PyTables/issues/73

**Comment by sbusard** [comment]
Thank you for pointing out these issues.

The LD_LIBRARY_PATH problem seems effectively difficult. Note that the second link you give does not solve exactly this problem as, in theirs, LD_LIBRARY_PATH is correctly set, but the setup.py script does not see it. This does not solve our current problem as we need to find a way to set LD_LIBRARY_PATH. As your first link points it out, the problem is really platform-specific.

**Comment by MatthieuPERIN** [comment]
You are right, the second link is not a solution to the problem of setting the LD_LIBRARY_PATH, I misread it !

I also understand that a platform specific version is out of the scope for the whole set of distribution possible, but if possible and you need help on that, it might be possible to implement it for the major platform such as linux Debian family (ubuntu) and windows ?

**Comment by sbusard** [comment]
First, I am not sure that PyNuSMV works on Windows. I have no Windows machine so I cannot check that everything works fine on it.

Second, I am not an expert for that matter, but I do not think that there are many solutions even if we only target Debian systems:
- updating LD_LIBRARY_PATH (or DYLD_LIBRARY_PATH on Mac OS) must be done in .bashrc (or similar); I am not sure setup.py has access to it.
- setup.py could link libnusmv.so into standard paths (such as /usr/lib/ ?), but I guess it needs root access.
