### ISSUE TITLE
Proposal for indentation in the NuSMV code generated

### ISSUE THREAD

**Issue by MatthieuPERIN** [sbusard/pynusmv#5]
Hi, 

When modeling a J/K memory:

``` python
from pynusmv.model import *


class main(Module):

    J = Var(Boolean(), "J")
    K = Var(Boolean(), "K")
    Q = Var(Boolean(), "Q")

    INIT = [(Q == Falseexp())]

    ASSIGN = {Next(Q): Case(((J & K, ~Q),
                             (J, Trueexp()),
                             (K, Falseexp()),
                             (Trueexp(), Q)))}

print(main)
```

The result in good as syntax but hardly readable:

```
MODULE main
    VAR
        J: boolean;
        K: boolean;
        Q: boolean;
    INIT
        Q = FALSE
    ASSIGN
        next(Q) := case
J & K: ! Q;
J: TRUE;
K: FALSE;
TRUE: Q;
esac;
```

As the case in rendered not following the indentation.

A solution might be to set a global variable "indetation_level" in class `ListingSection` or `Section` that is used by all instances and incremented when "giving hand" on sub elements (like form ListingSection to the `element` that constitue them) and removing indentation when giving execution back to the higher level.

Another solution is to work directly on the output of case to add indentation but it might be more difficult and far less elegant.

**Comment by sbusard** [comment]
The implemented solution is to put cases on new lines and to indent bodies of Sections (MappingSection, ListingSection). The result for the example is now

```
MODULE main
    VAR
        J: boolean;
        K: boolean;
        Q: boolean;
    INIT
        Q = FALSE
    ASSIGN
        next(Q) := 
            case
                J & K: ! Q;
                J: TRUE;
                K: FALSE;
                TRUE: Q;
            esac;
```

**Comment by MatthieuPERIN** [comment]
~~OK, maybe using the code include will give better result on github :)~~

PERFECT ! :+1:
