### ISSUE TITLE
Evaluate possibility to add comment in the generated NuSMV code

### ISSUE THREAD

**Issue by MatthieuPERIN** [sbusard/pynusmv#7]
The generator work perfectly to generate NuSMV code using the `model` package but, as usual with generated code, the result files may sometime lack readability.

A solution might be to add comment to the generated code.

This solution might no be easily implementable as the `model` package is intended to model NuSMV object solely, but it could be realized maybe:
- By adding a comment subsection on each section (IVAR, ASSIGN, ...)
- by adding a 'verbatim' capability than allow to add whenever the user what some hand written code, in our case comments, and add this to any declared sections.

Thanks again for the great work done !

**Comment by sbusard** [comment]
The `pyparsing` parser provided in `pynusmv.parser` can parse any part of a NuSMV model and is used when treating a model defined with the `pynusmv.model` package. More precisely, any part of an `Expression`, a `Module` a section in a module can be a string and will be parsed as the type of part it should represent. This means that there already exists a 'verbatim' capability that allow to add hand written code in Python-defined NuSMV models.

Nevertheless, this parser ignores the comments, and thus cannot be used directly to store the comments. So, this does not give a solution to the issue.

**Comment by sbusard** [comment]
A solution I see is to be able to associate a comment to any expression, section or module of a Python-defined NuSMV model. Sections (such as `TRANS`) are just lists of expressions, thus I guess associating a comment to a module or an expression should be enough.

The `Module` case is simple:

```
class main(pynusmv.model.Module):
    COMMENT = "This is the main module"
    myvar = pynusmv.model.Boolean()
    INIT = [~myvar]
    TRANS = [myvar.next()]
```

would result in:

```
module main():
    -- This is the main module
    VAR
        myvar: boolean;
    INIT
        !myvar
    TRANS
        next(myvar)
```

I think the solution is simple and intuitive as it uses a construct similar to what already exists to attach a comment to a module, and displaying this comment is quite straightforward as just after the "signature" of the module seems a good solution to me.

Note that the position of the comment must be arbitrary as Python does not retain the order in which the member of a class (`COMMENT`, `INIT`, etc.) are declared.

**Comment by sbusard** [comment]
The `Expression`case is more difficult. First, we need to define a way to attach a comment to an expression. It could be through its constructor, but not necessarily. I think that adding an argument to the constructor would not be the best solution, but I do not have one for now.

Second, we need to define where to print this comment. I think the simplest solutions are either printing the expression on a new line and adding the comment just above or below, on another line, or we could also print the comment at the end of the line on which the expression is (and either isolate the expression on its own line, or just keep it where it is).

**Comment by sbusard** [comment]
Finally, we need to modify the parser to associate the comments to the closest expression, module, etc. I think this will be difficult as, for now, the parser uses the `pyparsing` functionality to ignore the comments. If we want to keep them, we need to allow them to be anywhere in the parsed text, but still be able to manage them. I do not see a simple solution to this problem.

**Comment by MatthieuPERIN** [comment]
@sbusard Thanks for the answers.

I agree on the fact that a COMMENT section could be very useful, to my I will prefer to have a sort of "header" of the model like 

``` python
class main(pynusmv.model.Module):
    COMMENT = "----/n This is the main module/n ----"
    myvar = pynusmv.model.Boolean()
    INIT = [~myvar]
    TRANS = [myvar.next()]
```

Will produce

``` nusmv
------
-- This is the main module
------
module main():
    VAR
        myvar: boolean;
    INIT
        !myvar
    TRANS
        next(myvar)
```

But this is a purely cosmetic point of view.

For the rest I would love to have something than can produce line like that (inline comments in case)

```
next(mode):= case
  (mode=OFF) & condition_1 : OFF ; -- heater stay OFF
  (mode=OFF) & condition_2 : STARTUP ; -- heater detect potential need, startup
  (mode=STARTUP) & condition_3 : HEAT ; -- heater produce heat
  (mode=HEAT) & condition_4 : OFF ; --heater stop
  TRUE : mode;
esac;
```

But I agree with you on the fact that it is difficult to implement has the `pyparsing` module is meant to drop the comment . Is there any way to add in Python a new operator `--` and store comment in a specific line-ending `expresssion` that will be dropped by `pyparsing` but stored at another place during runtime ?

**Comment by sbusard** [comment]
# Modules

We agree that for the modules, it is easy.

# Others

For other parts of a module, there are two kinds to handle:
1. the simple expression, that is rendered on the current line (such as identifiers, boolean connectors, etc.) This covers almost all parts except modules and the ones covered by point 2.
2. the multi-line parts, such as case and VAR. This covers the Case expression and the mapping sections (VAR, IVAR, FVAR, DEFINE, ASSIGN).

The solution I propose for the first one is simply to write the associated comment(s) on the same line, ending with a new line.
The second case is, in my opinion, trickier. I suggest to simply write the comment(s) associated to the right part of each element at the end of its line.

# Parser

As far as I know, Python cannot define a new `--` operator. Furthermore, the parser have to do the job: it is the parser that will handle the text, and we need to modify it to keep the ignored comments. I think the problem is tricky, I suggest to keep the parser as it is for now.

# Example

To summarize, here is an example:

```
class main(pynusmv.model.Module):
    COMMENT = "This is the main module"

    myvar = pynusmv.model.Var(pynusmv.model.Boolean())
    Comment(myvar, "My variable")

    var2 = pynusmv.model.Identifier("var2")
    VAR = {var2: Comment(pynusmv.model.Range(0, 3), "The counter")}

    INIT = [Comment(~myvar, "myvar is false") &
            Comment(var2 == 0, "we start at 0")]

    TRANS = [
             pynusmv.model.Case(((myvar,
                                  Comment(
                                  Comment(var2.next() == ((var2 + 1) % 4),
                                          "Increase var2"),
                                  "Only when myvar is true"
                                  )
                                 ),
                                 (pynusmv.model.Trueexp(),
                                  Comment(var2.next() == var2,
                                          "otherwise do nothing"))))
            ]
```

and the result would be

```
-- This is the main module
module main():
    VAR:
        myvar: boolean; -- My variable
        var2: 0 .. 3; -- The counter
    INIT
        !myvar -- myvar is false
        & var2 = 0 -- we start at 0
    TRANS
        case
            myvar: next(var2) = (var2 + 1) % 4; -- Increase var2
            -- Only when myvar is true
            TRUE: next(var2) = var2; -- otherwise do nothing
        esac;
```

# Summary
- The `COMMENT` value of a module becomes its header.
- For the other parts, we attach a (set of) comment(s) with the `Comment` construct.
- The comment of an expression is displayed after the expression (with a new line).
- For mutli-line parts (Case and mapping sections), the comments of the right part (if any) are displayed after the corresponding line.
- The parser is kept as it is for now, simply ignoring the comments.

**Comment by MatthieuPERIN** [comment]
Hi,

Thanks you again for taking time to investigate my request (I know the time tat it can take for a 'simple' request).

your proposition sounds great to me and should fulfill completely my requests.

Do you want to implement them in a separated branch and need help to test them ?

**Comment by sbusard** [comment]
I implemented the functionalities described in my previous answer. The only difference is that the comment must be put on the type of a declaration instead of the declaration itself. Thus, the given example becomes (see the definition of `myvar`):

```
class main(pynusmv.model.Module):
    COMMENT = "This is the main module"

    myvar = pynusmv.model.Var(pynusmv.model.Comment(pynusmv.model.Boolean(),
                                                    "My variable"))

    var2 = pynusmv.model.Identifier("var2")
    VAR = {var2: pynusmv.model.Comment(pynusmv.model.Range(0, 3),
                                       "The counter")}

    INIT = [pynusmv.model.Comment(~myvar, "myvar is false") &
            pynusmv.model.Comment(var2 == 0, "we start at 0")]

    TRANS = [
             pynusmv.model.Case(((myvar,
                                  pynusmv.model.Comment(
                                  pynusmv.model.Comment(var2.next() ==
                                                        ((var2 + 1) % 4),
                                                        "Increase var2"),
                                  "Only when myvar is true")
                                 ),
                                 (pynusmv.model.Trueexp(),
                                 pynusmv.model.Comment(var2.next() == var2,
                                                       "otherwise do nothing"))
                                 ))
            ]
```

and the result is (almost) identical to the given one:

```
-- This is the main module
MODULE main
    VAR
        myvar: boolean; -- My variable
        var2: 0 .. 3; -- The counter
    INIT
        ! myvar -- myvar is false
        & var2 = 0 -- we start at 0
    TRANS
        case
            myvar: next(var2) = (var2 + 1) mod 4; -- Increase var2
            -- Only when myvar is true
            TRUE: next(var2) = var2; -- otherwise do nothing
        esac
```
