### ISSUE TITLE
gcc command doesn't continue when it gets to this file of compileWriteUdg.c

### ISSUE THREAD

**Issue by uammau** [sbusard/pynusmv#8]
running the make in the nusmv folder it just freezes and doesn't give any error. The other objects were created until this one.

**Comment by uammau** [comment]
The problem might be related to that I have linux 64 bits and maybe everything is ran in a 32 bits?

**Comment by uammau** [comment]
I get until the same point in ubuntu 14.04 32 bits as well.

**Comment by sbusard** [comment]
The problem comes from NuSMV compilation and has nothing to do with PyNuSMV.
I replicated the problem with NuSMV compilation on a fresh install of Ubuntu 14.04 32 bits.

**Comment by sbusard** [comment]
The solution, given in https://list.fbk.eu/sympa/arc/nusmv-users/2013-10/msg00004.html, is to disable GCC optimisation. For this, simply remove the -O2 options in pynusmv/src/nusmv/src/compile/Makefile (at lines 183 and 189 on my tests).

The compilation will then run smoothly.
