### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by markNZed** [sbusard/pynusmv#9]
Hi,

https://github.com/sbusard/pynusmv/blob/master/README line 140 PYTHON_PATH should be PYTHONPATH ?

I needed to manually install pyparsing maybe because pip3 was not being used (I did not look into this)

I'm building on Ubuntu 16.04

**Comment by sbusard** [comment]
Hello,

Yes, PYTHON_PATH should be PYTHONPATH. I will update the README file right now.

You can effectively install pyparsing by yourself, but pyparsing is anyway included beside pynusmv if it is not already installed.

**Comment by markNZed** [comment]
Hi, 

The README states:

If you to be able to access to PyNuSMV from anywhere, you have to set two
different environment variables:

    - LD_LIBRARY_PATH (or DYLD_LIBRARY_PATH under Mac OS) must contain the path
      to the src/lib/ directory of PyNuSMV package.
    - PYTHONPATH must contain the path to the src/ directory of PyNuSMV
      package.

So maybe add that pyparsing needs to be installed too.

**Comment by sbusard** [comment]
It is not necessary to install pyparsing as the building process of pynusmv should include pyparsing beside pynusmv when the latter is compiled. Are you saying that pyparsing is not included beside pynusmv if it is not already installed?

**Comment by sbusard** [comment]
Note that pyparsing is mentioned as a dependency at Line 32 of the README file: https://github.com/sbusard/pynusmv/blob/master/README#L32

**Comment by markNZed** [comment]
Hmm. Maybe I saw that problem because PYTHONPATH was not setup correctly. I installed it system wide so that error went away, then I was seeing the next error related to pynusmv and it was then I realised PYTHON_PATH was incorrect. I think you are right that PYTHONPATH will fix it. Sorry you can ignore me :)

**Comment by sbusard** [comment]
Yes, setting up PYTHONPATH instead of PYTHON_PATH should solve the problem of missing pyparsing, as pyparsing is included in the same directory as pynusmv (in the case it has not been installed before). Correctly setting PYTHONPATH will thus expose pyparsing and pynusmv at the same time.

Thank you for your feedback :)
